allowBuilds:
  '@parcel/watcher': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - antd@6.5.3
  - lint-staged@17.3.0
overrides:
  dompurify: 3.4.12
  postcss: 8.5.25
  sharp: 0.35.3
