import {
  BinaryIcon,
  BracesIcon,
  CalendarClockIcon,
  CaseSensitiveIcon,
  Clock3Icon,
  Code2Icon,
  DatabaseIcon,
  FileCodeIcon,
  FileJson2Icon,
  FileSpreadsheetIcon,
  FileUpIcon,
  GitCompareArrowsIcon,
  HashIcon,
  KeyRoundIcon,
  LinkIcon,
  LocateFixedIcon,
  type LucideIcon,
  NetworkIcon,
  PaletteIcon,
  QrCodeIcon,
  RadioTowerIcon,
  RegexIcon,
  ScanSearchIcon,
  ScanTextIcon,
  ShieldCheckIcon,
  SquareSplitHorizontalIcon,
  TextCursorInputIcon,
} from 'lucide-react';

export type ToolGroupKey =
  | 'code'
  | 'data'
  | 'javascript'
  | 'json'
  | 'text'
  | 'kits';

export interface ToolCatalogItem {
  description: string;
  group: ToolGroupKey;
  href: string;
  icon: LucideIcon;
  keywords: string[];
  title: string;
}

export const toolGroups: Array<{ key: ToolGroupKey; label: string }> = [
  { key: 'code', label: '代码' },
  { key: 'data', label: '数据' },
  { key: 'javascript', label: 'JavaScript' },
  { key: 'json', label: 'JSON' },
  { key: 'text', label: '文本' },
  { key: 'kits', label: '工具箱' },
];

export const toolCatalog: ToolCatalogItem[] = [
  {
    description: '并排检查文本或代码改动',
    group: 'code',
    href: '/code/diff',
    icon: SquareSplitHorizontalIcon,
    keywords: ['diff', 'compare', 'patch', '差异', '对比'],
    title: '代码对比',
  },
  {
    description: '整理常见代码与文本格式',
    group: 'code',
    href: '/code/format',
    icon: Code2Icon,
    keywords: ['format', 'prettier', 'beautify', '格式化', '美化'],
    title: '代码美化',
  },
  {
    description: '格式化、压缩与转换 JSON',
    group: 'json',
    href: '/json/stringify-parse',
    icon: BracesIcon,
    keywords: ['json', 'format', 'minify', 'escape', '格式化', '转义'],
    title: 'JSON 工作台',
  },
  {
    description: 'CSV 与扁平 JSON 数组双向转换',
    group: 'data',
    href: '/data/csv-json',
    icon: FileSpreadsheetIcon,
    keywords: ['csv', 'json', 'table', '表格', '转换'],
    title: 'CSV / JSON',
  },
  {
    description: '校验、格式化、压缩并执行 XPath',
    group: 'data',
    href: '/data/xml',
    icon: FileCodeIcon,
    keywords: ['xml', 'xpath', 'format', 'minify', '格式化', '查询'],
    title: 'XML',
  },
  {
    description: 'RFC 6901 查询和不可变修改 JSON',
    group: 'data',
    href: '/data/json-pointer',
    icon: LocateFixedIcon,
    keywords: ['json pointer', 'rfc6901', 'path', '路径', '查询', '修改'],
    title: 'JSON Pointer',
  },
  {
    description: '从 JSON 或 JavaScript 对象生成 TypeScript',
    group: 'javascript',
    href: '/js/to-ts',
    icon: FileJson2Icon,
    keywords: ['typescript', 'interface', 'type', '类型', '生成'],
    title: '转 TypeScript',
  },
  {
    description: '从 JSON 或 JavaScript 对象生成 JSON Schema',
    group: 'javascript',
    href: '/js/to-schema',
    icon: FileCodeIcon,
    keywords: ['json schema', 'schema', 'validation', '结构', '生成'],
    title: '转 JSON Schema',
  },
  {
    description: 'Base64、URL 与 HTML 实体双向转换',
    group: 'text',
    href: '/text/codec',
    icon: TextCursorInputIcon,
    keywords: ['base64', 'url encode', 'html entity', '编码', '解码'],
    title: '文本编码',
  },
  {
    description: '命名格式、空白与行级批量处理',
    group: 'text',
    href: '/text/transform',
    icon: CaseSensitiveIcon,
    keywords: ['camelcase', 'snake case', 'sort', 'dedupe', '命名', '行处理'],
    title: '文本处理',
  },
  {
    description: '匹配、捕获组与替换结果预览',
    group: 'text',
    href: '/text/regex',
    icon: RegexIcon,
    keywords: ['regex', 'regexp', 'match', 'replace', '正则', '匹配'],
    title: '正则测试',
  },
  {
    description: '代码点、编码、转义与归一化分析',
    group: 'text',
    href: '/text/unicode',
    icon: ScanTextIcon,
    keywords: ['unicode', 'utf8', 'utf16', 'normalize', '代码点', '归一化'],
    title: 'Unicode',
  },
  {
    description: 'SHA 摘要、UUID 与安全随机字符串',
    group: 'kits',
    href: '/kits/hash-random',
    icon: HashIcon,
    keywords: ['sha', 'hash', 'uuid', 'random', '哈希', '随机'],
    title: '哈希与随机值',
  },
  {
    description: '本地解析 Header、Payload 与时间 Claims',
    group: 'kits',
    href: '/kits/jwt',
    icon: ScanSearchIcon,
    keywords: ['jwt', 'token', 'claims', 'decode', '令牌', '解码'],
    title: 'JWT 解码',
  },
  {
    description: '使用 Web Crypto 生成消息认证码',
    group: 'kits',
    href: '/kits/hmac',
    icon: KeyRoundIcon,
    keywords: ['hmac', 'signature', 'sha256', '签名', '消息认证码'],
    title: 'HMAC',
  },
  {
    description: 'HEX、RGB、HSL 转换与 WCAG 对比度',
    group: 'kits',
    href: '/kits/color',
    icon: PaletteIcon,
    keywords: ['hex', 'rgb', 'hsl', 'wcag', 'contrast', '颜色', '对比度'],
    title: '颜色与对比度',
  },
  {
    description: 'SI 与 IEC 数据单位精确换算',
    group: 'kits',
    href: '/kits/data-size',
    icon: DatabaseIcon,
    keywords: ['byte', 'kb', 'mb', 'mib', 'size', '字节', '数据大小'],
    title: '数据大小',
  },
  {
    description: '八进制、符号权限与特殊位互转',
    group: 'kits',
    href: '/kits/chmod',
    icon: ShieldCheckIcon,
    keywords: ['chmod', 'permission', 'octal', 'unix', '权限', '八进制'],
    title: 'Unix 权限',
  },
  {
    description: '校验并解释标准五段 Cron 表达式',
    group: 'kits',
    href: '/kits/cron',
    icon: CalendarClockIcon,
    keywords: ['cron', 'schedule', '定时', '表达式', '计划任务'],
    title: 'Cron',
  },
  {
    description: '计算 IPv4 子网、主机范围与地址分类',
    group: 'kits',
    href: '/kits/ip-cidr',
    icon: NetworkIcon,
    keywords: ['ipv4', 'cidr', 'subnet', 'mask', 'ip', '子网', '掩码'],
    title: 'IPv4 / CIDR',
  },
  {
    description: '解析、比较、递增并判断版本范围',
    group: 'kits',
    href: '/kits/semver',
    icon: GitCompareArrowsIcon,
    keywords: ['semver', 'version', 'range', '版本', '比较', '递增'],
    title: 'SemVer',
  },
  {
    description: '文本与文件的 Data URL 编解码',
    group: 'kits',
    href: '/kits/data-url',
    icon: FileUpIcon,
    keywords: ['data url', 'base64', 'mime', 'file', '文件', '编码'],
    title: 'Data URL',
  },
  {
    description: '生成 cURL、Fetch 与原始 HTTP 请求',
    group: 'kits',
    href: '/kits/http-builder',
    icon: Code2Icon,
    keywords: ['http', 'curl', 'fetch', 'request', '请求', '代码生成'],
    title: 'HTTP 代码生成',
  },
  {
    description: '逐行解析事件流并预览派发结果',
    group: 'kits',
    href: '/kits/sse-preview',
    icon: RadioTowerIcon,
    keywords: [
      'sse',
      'server-sent events',
      'eventsource',
      'stream',
      '事件流',
      '流式',
    ],
    title: 'SSE 消息预览',
  },
  {
    description: '秒、毫秒时间戳与日期双向转换',
    group: 'kits',
    href: '/kits/timestamp',
    icon: Clock3Icon,
    keywords: ['timestamp', 'unix time', 'date', '时间戳', '日期'],
    title: '时间戳',
  },
  {
    description: '大整数二、八、十、十六进制互转',
    group: 'kits',
    href: '/kits/radix',
    icon: BinaryIcon,
    keywords: ['binary', 'octal', 'decimal', 'hex', '进制', '大整数'],
    title: '进制转换',
  },
  {
    description: '拆解 URL 与转换查询参数',
    group: 'kits',
    href: '/kits/url-parser',
    icon: LinkIcon,
    keywords: ['url', 'query', 'search params', '解析', '查询参数'],
    title: 'URL 解析',
  },
  {
    description: '生成并下载 Canvas 或 SVG',
    group: 'kits',
    href: '/kits/qrcode',
    icon: QrCodeIcon,
    keywords: ['qr', 'qrcode', 'canvas', 'svg', '二维码'],
    title: '二维码',
  },
];
